RENAME TABLE `User` TO `users`;
RENAME TABLE `Service` TO `services`;
RENAME TABLE `Package` TO `packages`;
RENAME TABLE `PackageService` TO `package_services`;
RENAME TABLE `Coupon` TO `coupons`;
RENAME TABLE `Order` TO `orders`;
RENAME TABLE `Subscription` TO `subscriptions`;
RENAME TABLE `Trip` TO `trips`;
RENAME TABLE `Booking` TO `bookings`;